App:
  Port: 8090

Database:
  DB_Connection: "mysql"
  DB_Host: "172.17.0.4"
  DB_Port: 3306
  DB_Name: "food-service"
  DB_Username: "root"
  DB_Password: "admin"
  DB_TIMEZONE: "Asia/Tehran"

Files:
  Path: "./files"

Jwt:
  Secret: "q1w2e3r4t5y6"